### ISSUE TITLE
the shortened url is not working correctly

### ISSUE THREAD

**Issue by vishal-mourya** [maw1a/Shortify#1]
The shortened URL which your URL shortener generates, is having one extra "htttps//" in its prefix.

I have fixed this issue in my local repo, if you want I can fix this issue or else you can fix this issue.

Hoping positive action from your side.

Thanks & Regards
Happy Open-Sourcing :)

**Comment by maw1a** [comment]
Thank you for pointing out this issue. There is no validation of the url format. This issue can be fixed with url validation and handling. You can create a PR if you would like to work on this.
